Mission 1 : Load the season and find our match (DataFrames, filters)

In [16]:
from statsbombpy import sb
import pandas as pd

matches = sb.matches(competition_id=2, season_id=27)

/home/vscode/.local/lib/python3.12/site-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

In [17]:
matches.shape

(380, 55)

In [3]:
matches.head(3)

,match_id,match_date,kick_off,home_score,away_score,match_status,match_status_360,last_updated,last_updated_360,match_week,...,home_manager_country_name,away_manager_id,away_manager_name,away_manager_nickname,away_manager_dob,away_manager_country_id,away_manager_country_name,data_version,shot_fidelity_version,xy_fidelity_version
0,3754217,2015-09-19,11:45:00.000,2,0,available,scheduled,2025-12-16T17:01:18.696515,2021-06-13T16:17:31.694,6,...,Portugal,577,Arsène Wenger,NaN,1949-10-22,78,France,1.1.0,2,2
1,3754117,2015-12-13,12:30:00.000,0,2,available,scheduled,2025-12-16T17:04:24.176407,2021-06-13T16:17:31.694,16,...,France,577,Arsène Wenger,NaN,1949-10-22,78,France,1.1.0,2,2
2,3754296,2015-12-21,19:00:00.000,2,1,available,scheduled,2025-12-17T11:59:35.059270,2021-06-13T16:17:31.694,17,...,France,733,Manuel Luis Pellegrini Ripamonti,Manuel Pellegrini,1953-09-16,45,Chile,1.1.0,2,2

In [4]:
list(matches.columns)

['match_id',
 'match_date',
 'kick_off',
 'home_score',
 'away_score',
 'match_status',
 'match_status_360',
 'last_updated',
 'last_updated_360',
 'match_week',
 'competition_id',
 'competition_country_name',
 'competition_name',
 'competition',
 'season_id',
 'season',
 'home_team_id',
 'home_team',
 'home_team_gender',
 'home_team_group',
 'home_team_country_id',
 'home_team_country_name',
 'away_team_id',
 'away_team',
 'away_team_gender',
 'away_team_group',
 'away_team_country_id',
 'away_team_country_name',
 'competition_stage_id',
 'competition_stage',
 'stadium_id',
 'stadium',
 'stadium_country_id',
 'stadium_country_name',
 'referee_id',
 'referee',
 'referee_country_id',
 'referee_country_name',
 'home_managers',
 'away_managers',
 'home_manager_id',
 'home_manager_name',
 'home_manager_nickname',
 'home_manager_dob',
 'home_manager_country_id',
 'home_manager_country_name',
 'away_manager_id',
 'away_manager_name',
 'away_manager_nickname',
 'away_manager_dob',
 'away_manager_country_id',
 'away_manager_country_name',
 'data_version',
 'shot_fidelity_version',
 'xy_fidelity_version']

In [19]:
is_home = matches['home_team'] == "Arsenal"
is_away = matches['away_team'] == "Everton"
game = matches[ is_home & is_away ]
game
game[['match_date', 'home_team', 'away_team', 'home_score', 'away_score']]

    match_date home_team away_team  home_score  away_score
94  2015-10-24   Arsenal   Everton           2           1

In [21]:
game.T

                                                   94
match_id                                      3754126
match_date                                 2015-10-24
kick_off                                 18:30:00.000
home_score                                          2
away_score                                          1
match_status                                available
match_status_360                            scheduled
last_updated               2022-12-01T13:14:32.244938
last_updated_360              2021-06-13T16:17:31.694
match_week                                         10
competition_id                                      2
competition_country_name                      England
competition_name                       Premier League
competition                  England - Premier League
season_id                                          27
season                                      2015/2016
home_team_id                                        1
home_team                                     Arsenal
home_team_gender                                 male
home_team_group                                  None
home_team_country_id                               68
home_team_country_name                        England
away_team_id                                       29
away_team                                     Everton
away_team_gender                                 male
away_team_group                                  None
away_team_country_id                               68
away_team_country_name                        England
competition_stage_id                                1
competition_stage                      Regular Season
stadium_id                                          3
stadium                              Emirates Stadium
stadium_country_id                                 68
stadium_country_name                          England
referee_id                                         10
referee                                     Lee Mason
referee_country_id                                 68
referee_country_name                          England
home_managers                           Arsène Wenger
away_managers               Roberto Martínez Montoliú
home_manager_id                                   577
home_manager_name                       Arsène Wenger
home_manager_nickname                             NaN
home_manager_dob                           1949-10-22
home_manager_country_id                            78
home_manager_country_name                      France
away_manager_id                                   263
away_manager_name           Roberto Martínez Montoliú
away_manager_nickname                Roberto Martínez
away_manager_dob                           1973-07-13
away_manager_country_id                           214
away_manager_country_name                       Spain
data_version                                    1.1.0
shot_fidelity_version                               2
xy_fidelity_version                                 2

In [24]:
pd.set_option('display.max_columns', None)
game

,match_id,match_date,kick_off,home_score,away_score,match_status,match_status_360,last_updated,last_updated_360,match_week,competition_id,competition_country_name,competition_name,competition,season_id,season,home_team_id,home_team,home_team_gender,home_team_group,home_team_country_id,home_team_country_name,away_team_id,away_team,away_team_gender,away_team_group,away_team_country_id,away_team_country_name,competition_stage_id,competition_stage,stadium_id,stadium,stadium_country_id,stadium_country_name,referee_id,referee,referee_country_id,referee_country_name,home_managers,away_managers,home_manager_id,home_manager_name,home_manager_nickname,home_manager_dob,home_manager_country_id,home_manager_country_name,away_manager_id,away_manager_name,away_manager_nickname,away_manager_dob,away_manager_country_id,away_manager_country_name,data_version,shot_fidelity_version,xy_fidelity_version
94,3754126,2015-10-24,18:30:00.000,2,1,available,scheduled,2022-12-01T13:14:32.244938,2021-06-13T16:17:31.694,10,2,England,Premier League,England - Premier League,27,2015/2016,1,Arsenal,male,None,68,England,29,Everton,male,None,68,England,1,Regular Season,3,Emirates Stadium,68,England,10,Lee Mason,68,England,Arsène Wenger,Roberto Martínez Montoliú,577,Arsène Wenger,NaN,1949-10-22,78,France,263,Roberto Martínez Montoliú,Roberto Martínez,1973-07-13,214,Spain,1.1.0,2,2

Mission 2: load events

In [29]:
match_id=game.iloc[0]['match_id']

In [33]:
events=sb.events(match_id=match_id)
events.shape

/home/vscode/.local/lib/python3.12/site-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

(3771, 91)

In [34]:
events['type'].value_counts()

type
Pass               1034
Ball Receipt*       969
Carry               854
Pressure            329
Ball Recovery       112
Duel                 77
Block                47
Dribble              45
Dispossessed         43
Clearance            38
Goal Keeper          34
Dribbled Past        33
Shot                 30
Foul Committed       29
Miscontrol           28
Foul Won             28
Interception         19
Substitution          5
Half Start            4
Half End              4
Injury Stoppage       3
Starting XI           2
Shield                1
Player Off            1
Player On             1
Tactical Shift        1
Name: count, dtype: int64

In [ ]:
Everton_shots=events[(events['type'] == "Shot") & (events['team'] == "Everton")]
len(Everton_shots)

10

In [67]:
Arsenal_shots=events[(events['type'] == "Shot") & (events['team'] == "Arsenal")]
len(Arsenal_shots)

20

In [69]:
Everton_Pass=events[(events['type'] == "Pass") & (events['team'] == "Everton")]
len(Everton_Pass)

458

In [70]:
pd.crosstab(events['type'], events['team'])

team             Arsenal  Everton
type
Ball Receipt*        545      424
Ball Recovery         52       60
Block                 25       22
Carry                512      342
Clearance             16       22
Dispossessed          32       11
Dribble               23       22
Dribbled Past         16       17
Duel                  26       51
Foul Committed        13       16
Foul Won              15       13
Goal Keeper           12       22
Half End               2        2
Half Start             2        2
Injury Stoppage        2        1
Interception          11        8
Miscontrol            12       16
Pass                 576      458
Player Off             0        1
Player On              0        1
Pressure             114      215
Shield                 0        1
Shot                  20       10
Starting XI            1        1
Substitution           2        3
Tactical Shift         1        0

In [68]:
Arsenal_Pass=events[(events['type'] == "Pass") & (events['team'] == "Arsenal")]
len(Arsenal_Pass)

576